import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Message } from '../types';
import { User, Bot } from 'lucide-react';

interface ChatMessageProps {
  message: Message;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const isUser = message.role === 'user';

  return (
    <div className={`flex w-full mb-6 ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div className={`flex max-w-[85%] md:max-w-[75%] gap-4 ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>
        
        {/* Avatar */}
        <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
          isUser ? 'bg-indigo-600' : 'bg-emerald-600'
        }`}>
          {isUser ? <User className="w-5 h-5 text-white" /> : <Bot className="w-5 h-5 text-white" />}
        </div>

        {/* Bubble */}
        <div className={`flex flex-col ${isUser ? 'items-end' : 'items-start'}`}>
          <div className={`px-5 py-3.5 rounded-2xl shadow-sm text-sm leading-relaxed ${
            isUser 
              ? 'bg-indigo-600 text-white rounded-tr-sm' 
              : 'bg-white border border-slate-100 text-slate-700 rounded-tl-sm'
          }`}>
             {message.text ? (
                <div className="markdown-body">
                   <ReactMarkdown 
                      components={{
                        code({node, className, children, ...props}) {
                          const match = /language-(\w+)/.exec(className || '')
                          return match ? (
                            <div className="bg-slate-900 text-slate-100 rounded-md p-3 my-2 text-xs font-mono overflow-x-auto">
                                <code className={className} {...props}>
                                  {children}
                                </code>
                            </div>
                          ) : (
                            <code className="bg-slate-100 text-slate-800 px-1 py-0.5 rounded font-mono text-xs" {...props}>
                              {children}
                            </code>
                          )
                        }
                      }}
                   >
                     {message.text}
                   </ReactMarkdown>
                </div>
             ) : message.imageUrl ? (
               // Used for displaying images generated by the model
               <img src={message.imageUrl} alt="Generated content" className="rounded-lg max-w-sm border border-slate-200" />
             ) : (
                <span className="italic opacity-70">Typing...</span>
             )}
          </div>
          {/* Timestamp or Status */}
          <span className="text-xs text-slate-400 mt-1 px-1">
            {isUser ? 'You' : 'Leona'} • {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </span>
        </div>

      </div>
    </div>
  );
};

export default ChatMessage;